version: '3.8'
services:
  postgres:
    image: postgres:14
    env_file:
      - '.envrc'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: node:16
    command: sh -c "yarn start:prod"
    working_dir: /newor/newor-api
    volumes:
      - ./:/newor/newor-api
    env_file:
      - '.envrc'
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
