version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - '.envrc'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: node:16
    command: sh -c "yarn start:prod"
    working_dir: /newor/newor-api
    volumes:
      - ./:/newor/newor-api
    env_file:
      - '.envrc'
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - 6831:6831/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
    networks:
      - jaegerdata
volumes:
  pgdata:
networks:
  jaegerdata:
