name: Build & Deply Dev
on:
  workflow_run:
    workflows: [Validate]
    types: [completed]
jobs:
  build:
    name: build
    env:
      DEV_EC2_PRIVATE_KEY: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
      DEV_EC2_USERNAME: ${{ secrets.DEV_EC2_USERNAME }}
      DEV_EC2_HOSTNAME: ${{ secrets.DEV_EC2_HOSTNAME }}
      GIT_OWNER: ${{ secrets.GIT_OWNER }}
      GIT_CONFIG_REPOSITORY: ${{ secrets.GIT_CONFIG_REPOSITORY }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: clean
        run: |
          echo "$DEV_EC2_PRIVATE_KEY" > newor_dev.pem && chmod 400 newor_dev.pem
          ssh -o StrictHostKeyChecking=no -i newor_dev.pem ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME} '
            cd ~/newor/newor-api
            docker-compose down
            sudo rm -rf ~/newor && mkdir -p ~/newor/newor-api
          '
      - name: get config
        run: |
          export OWNER=GIT_OWNER
          export CONFIG_REPOSITORY=GIT_CONFIG_REPOSITORY
          export DEPLOY_ENV=dev
          export TOKEN=GIT_TOKEN
          yarn appconfig
      - name: copy files
        run: |
          scp -r -i newor_dev.pem ./* ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME}:~/newor/newor-api
          scp -i newor_dev.pem ./.envrc ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME}:~/newor/newor-api/.envrc
          scp -i newor_dev.pem ./.dockerignore ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME}:~/newor/newor-api/.dockerignore
          scp -i newor_dev.pem ./.sequelizerc ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME}:~/newor/newor-api/.sequelizerc
  deploy:
    name: deploy
    env:
      DEV_EC2_PRIVATE_KEY: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
      DEV_EC2_USERNAME: ${{ secrets.DEV_EC2_USERNAME }}
      DEV_EC2_HOSTNAME: ${{ secrets.DEV_EC2_HOSTNAME }}
    needs: build
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: docker compose
        run: |
          echo "$DEV_EC2_PRIVATE_KEY" > newor_dev.pem && chmod 400 newor_dev.pem
          ssh -o StrictHostKeyChecking=no -i newor_dev.pem ${DEV_EC2_USERNAME}@${DEV_EC2_HOSTNAME} '
            cd ~/newor/newor-api
            docker-compose up -d
          '