name: Build-Dev
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOSTNAME }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_PRIVATE_KEY }}
          source: "./"
          target: "/newor/newor-api"
